stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - ls -la
  - ''
  - echo "Restoring NuGet Packages..."
  - '"c:\nuget\nuget.exe" restore "LightsOut\LightsOut.sln"'
  - ''
  - echo "Debug build..."
  - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe /consoleloggerparameters:ErrorsOnly
    /maxcpucount /nologo /property:Configuration=Debug /verbosity:quiet "LightsOut\LightsOut.sln"
  - ''
  - echo "Release build..."
  - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe /consoleloggerparameters:ErrorsOnly
    /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "LightsOut\LightsOut.sln"
  - ''
  - echo "Build success."
  tags: 
  except:
  - tags